### ISSUE TITLE
No ability to includePaths

### ISSUE THREAD

**Issue by wardpenney** [unlight/gulp-cssimport#11]
I may be doing this wrong, but why does gulp-cssimport not have an option for `includePaths` which gulp-sass has?

I am trying to do something like this:

```JavaScript
var gulp = require("gulp"),
    cssimport = require("gulp-cssimport"),
    bourbonPaths = require("node-bourbon").includePaths,
    sourceFilename = "scss/source.scss.liquid",
    destinationFolder = "assets/";

gulp.task("styles", function(){
  return gulp.src([sourceFilename])
    .pipe(cssimport(includePaths: bourbonPaths))
    .pipe(gulp.dest(destinationFolder));
})
```

I'm trying to use node-bourbon.

Edit: Add more to the source example.

**Comment by unlight** [comment]
I'm not sure that it is the right way of usage.
Why are you not using gulp-sass?

**Comment by wardpenney** [comment]
The recommendation came from Shopify's example repo at https://github.com/Shopify/shopify-css-import to use `gulp-cssimport`. I am guessing they don't use `gulp-sass` because the files need to actually be `liquid` as the last file extension. When I try to use `gulp-sass` I get an error saying the source file is invalid.

**Comment by unlight** [comment]
Maybe [directory option](https://www.npmjs.com/package/gulp-cssimport#directory) can help, it will act as current working directory.
```js
gulp.task("styles", function(){
  return gulp.src([sourceFilename])
    .pipe(cssimport(directory: bourbonPaths[0]))
    .pipe(gulp.dest(destinationFolder));
})
```
Note: `directory` is string, so you can specify on 1 path.

Not tested this.

**Comment by wardpenney** [comment]
Ohh that is close! But it looks like the `directory` option is not respected or something:

```no-highlight
[14:27:23] WARDTEST: /Users/wardpenney/test-app/node_modules/node-bourbon/node_modules/bourbon/app/assets/stylesheets
Trace: { [Error: ENOENT, open '/Users/wardpenney/test-app/scss/bourbon']
  errno: 34,
  code: 'ENOENT',
  path: '/Users/wardpenney/test-app/scss/bourbon' }
    at onResolvePath (/Users/wardpenney/test-app/node_modules/gulp-cssimport/gulp-cssimport.js:85:13)
    at /Users/wardpenney/test-app/node_modules/gulp-cssimport/helper.js:94:3
    at fs.js:207:20
    at Object.oncomplete (fs.js:107:15)

/Users/wardpenney/workspace/test-app/node_modules/gulp-cssimport/gulp-cssimport.js:86
				throw err;
				      ^
Error: ENOENT, open '/Users/wardpenney/test-app/scss/bourbon'
```

**Comment by unlight** [comment]
You are right, directory is ignored if object is vinyl file.

**Comment by unlight** [comment]
gulp-cssimport can work with plain string/buffer streams.
```js
var through2 = require("through2");
var VinylFile = require('vinyl');

	var stream = gulp.src("design/style.css")
		.pipe(through2.obj(function (chunk, enc, callback) {
			var ch = Chunk.create({
				contents: chunk.contents.toString(),
				directory: chunk.base
			});
			callback(null, ch);
		}))
		.pipe(cssimport({directory: "design" }))
		.pipe(through2.obj(function (data, enc, callback) {
			var file = new VinylFile({
				path: 'x', // <--- we lost path here.
				contents: new Buffer(data)
			});
			callback(null, file);
		}))
		.pipe(gulp.dest("/dev/null"));
```
It works for me, but there is a problem - we lost file name. Need solve this somehow.

**Comment by wardpenney** [comment]
What if we just use a variable to hold the filename?

```
var gulp = require("gulp"),
    cssimport = require("gulp-cssimport"),
    through2 = require("through2"),
    VinylFile = require('vinyl'),
    neatPaths = require("node-neat").includePaths,
    bourbonPaths = require("node-bourbon").includePaths,
    sourceFilename = "scss/styles.scss.liquid",
    destinationFolder = "assets/",
    Chunk = require("gulp-cssimport/chunk");

gulp.task("styles", function(){
  return gulp.src([sourceFilename])
    .pipe(through2.obj(function (chunk, enc, callback) {
        var ch = Chunk.create({
            contents: chunk.contents.toString(),
            directory: chunk.base
        });
        callback(null, ch);
    }))
    .pipe(cssimport({directory: bourbonPaths[0]}))
    .pipe(through2.obj(function (data, enc, callback) {
        var file = new VinylFile({
            path: sourceFilename, // <- Can we just use a filename variable?
            contents: new Buffer(data)
        });
        callback(null, file);
    }))
    .pipe(gulp.dest(destinationFolder));
})

gulp.task("watch", function () {
  gulp.watch("scss/**/*.*", ["styles"]);
});

gulp.task("default", ["watch"]);

```

Thanks for all your help, btw

**Comment by unlight** [comment]
If you are building 1:1from single source file then yes it is a solution.
But I will think how to improve this stuff.
